/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.clsControlador;
//import Controlador.interfazControlador;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.omg.CORBA.ORB;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.InvalidName;
import org.omg.CosNaming.NamingContextPackage.NotFound;
import sop_corba.UsuarioDTO;
import sop_corba.anteproyectoDTO;
import sop_corba.clsAsigEvaluadoresDTO;
import sop_corba.interfazEstudiantesDirectorHelper;
import sop_corba.interfazEstudiantesDirectorOperations;
import sop_corba.interfazEvaluadorHelper;
import sop_corba.interfazEvaluadorOperations;
import sop_corba.interfazJefeDepartamentoHelper;
import sop_corba.interfazJefeDepartamentoOperations;
import sop_corba.interfazUsuarioHelper;
import sop_corba.interfazUsuarioOperations;

/**
 *
 * @author Angélica
 */
public class InterfazIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static interfazJefeDepartamentoOperations ref_servicios_jefe;
    static interfazUsuarioOperations ref_servicios_IniciarSesion;
    static interfazEvaluadorOperations ref_asignar_evaluadores;
    static interfazEstudiantesDirectorOperations ref_estudiantes;
    private final static int ESTUDIANTE_DIRECTOR = 1;
    private final static int EVALUADOR = 2;
    private final static int JEFE_DEPARTAMENTO = 3;
    
    
    //interfazControlador objControlador = null;
    InterfazAdministrador InterfazAdministrador = null;
    InterfazEstudianteDirector InterfazEstudianteDirector = null;
    InterfazEvaluador InterfazEvaluador = null;
    
    public InterfazIniciarSesion() throws RemoteException {
        centrarVentanaLogin();
        //this.objControlador = new clsControlador();
        initComponents();
    }

    public void centrarVentanaLogin(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);		
        setLocationRelativeTo(null);		
    }
    
    public void iniciarSesion() throws RemoteException, IOException{
        int tipoDeUsuario = 0;
        String usuario = this.jtfUsuario.getText().trim();
        String contrasenia = this.jtfContrasenia.getText().trim();
        tipoDeUsuario = ref_servicios_IniciarSesion.IniciarSesion(usuario,contrasenia);
        switch(tipoDeUsuario){
            case ESTUDIANTE_DIRECTOR:
                this.setVisible(false);
                this.InterfazEstudianteDirector = new InterfazEstudianteDirector();
                InterfazEstudianteDirector.iniRef(ref_estudiantes);
                this.InterfazEstudianteDirector.setVisible(true);
                break;
            case EVALUADOR:
                this.setVisible(false);
                this.InterfazEvaluador = new InterfazEvaluador();
                
                this.InterfazEvaluador.setVisible(true);
                break;
            case JEFE_DEPARTAMENTO:
                this.setVisible(false);
                this.InterfazAdministrador = new InterfazAdministrador();
                this.InterfazAdministrador.setVisible(true);
                break;
            default:
                this.setVisible(true);
                JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado", "Usuario no encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }
     private boolean hayCamposVaciosEnIniciarSesion() {
        return (this.jtfUsuario.getText().isEmpty() || this.jtfContrasenia.getText().isEmpty());
    }

    private void limpiarCamposEnIniciarSesion() {
        this.jtfUsuario.setText("");
        this.jtfContrasenia.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jtfContrasenia = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarte = new javax.swing.JButton();
        lblInfoApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatosLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 153));
        lblUsuario.setText("Usuario");

        lblContrasenia.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 153));
        lblContrasenia.setText("Contraseña");

        javax.swing.GroupLayout pnlDatosLoginLayout = new javax.swing.GroupLayout(pnlDatosLogin);
        pnlDatosLogin.setLayout(pnlDatosLoginLayout);
        pnlDatosLoginLayout.setHorizontalGroup(
            pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasenia)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfContrasenia)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLoginLayout.setVerticalGroup(
            pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLoginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDatosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(jtfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistrarte.setText("REGISTRARTE");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarte)
                .addGap(64, 64, 64))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnRegistrarte))
                .addContainerGap())
        );

        lblInfoApp.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblInfoApp.setForeground(new java.awt.Color(0, 0, 153));
        lblInfoApp.setText("GESTION ANTEPROYECTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblInfoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoApp)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        if(!hayCamposVaciosEnIniciarSesion()){
            try {
                iniciarSesion();
            } catch (IOException ex) {
                Logger.getLogger(InterfazIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiarCamposEnIniciarSesion();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NotFound, CannotProceed, InvalidName, org.omg.CORBA.ORBPackage.InvalidName {
        // crea e inicia el ORB
            // crea e iniciia el ORB
            String[] vector = new String[]{"-ORBInitialHost", "localhost", "-ORBInitialPort", "2020"};
            ORB orb = ORB.init(vector, null);

            // obtiene la base del naming context
            org.omg.CORBA.Object objRef = 
            orb.resolve_initial_references("NameService");
            
            //->>>>>>>>>>>>>>>>>>>>>>>>>>>para REgistra usuario>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            NamingContextExt ncRef = NamingContextExtHelper.narrow(objRef);
            ref_servicios_jefe = interfazJefeDepartamentoHelper.narrow(ncRef.resolve_str("ServiciosJefe"));
           // UsuarioDTO obj = new UsuarioDTO("100", "rene","jalvin", "rene","1299",1);
            //ref_servicios_jefe.RegistrarUsuario(obj);             //modalidad//titulo//idanterpoyecto//idcoordiandor//
            //->>>>>>>>>>>>>>>>>>>>>>>>>>>>>para registar anteproyecto>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            //anteproyectoDTO objAnteproyecto = new anteproyectoDTO(_atrModalidad, _atrTitulo,codigoAnteproyecto, _atrIdEstudiante1, _atrIdEstudiante2, _atrIdDirector, _atrIdCodirector, _atrFechaRegistro, _atrFechaAprobacion,concepto,estado,numRevicion);
            anteproyectoDTO objAnteproyecto = new anteproyectoDTO("mod",              "cor",          85,               "15",               "2",               "3",           "21",           "12/12/12",         "12/12/12",         2,       2,    145);
            //ref_servicios_jefe.RegistarAnteProyectos(objAnteproyecto);
            //->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>para AsignarEvaluadores>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            clsAsigEvaluadoresDTO objAsigEvaluadores = new clsAsigEvaluadoresDTO(85, "20", "2", "12/12/12", "21", "2", "12/12/12");
            //ref_servicios_jefe.AsignarEvaluadores(objAsigEvaluadores);
            //->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>para iniciar sesion>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
             org.omg.CORBA.Object objRefIniciarSesion = orb.resolve_initial_references("NameService");
            NamingContextExt ncRefIniciarSesion = NamingContextExtHelper.narrow(objRefIniciarSesion);
            ref_servicios_IniciarSesion = interfazUsuarioHelper.narrow(ncRefIniciarSesion.resolve_str("IniciarSesion"));
            //int a = ref_servicios_IniciarSesion.IniciarSesion("rene", "1299");
            //System.out.println("tipo usuario : "+a);
            //->>>>>>>>>>>>>>>>>>>>>>>>>>>>>modificar concepto>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            org.omg.CORBA.Object objRefAsignarEvaluadores = orb.resolve_initial_references("NameService");
            NamingContextExt ncRefAsignarEvaluadores = NamingContextExtHelper.narrow(objRefAsignarEvaluadores);
              ref_asignar_evaluadores = interfazEvaluadorHelper.narrow(ncRefAsignarEvaluadores.resolve_str("serviciosEvaluador"));
              //ref_asignar_evaluadores.ingresarConceptoEvaluador(3,85,1);
            //>>>>>>>>>>>>>>>>>>>>>>>>>>>listarAnteproyectos>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
             org.omg.CORBA.Object objRefListAnteproyectos = orb.resolve_initial_references("NameService");
            NamingContextExt ncRefListaAnteproyectos = NamingContextExtHelper.narrow(objRefListAnteproyectos);
              ref_estudiantes = interfazEstudiantesDirectorHelper.narrow(ncRefListaAnteproyectos.resolve_str("serviciosEstudianes"));
              //ref_estudiantes.listarAnteProyectos();
            

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazIniciarSesion().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(InterfazIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarte;
    private javax.swing.JTextField jtfContrasenia;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblInfoApp;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatosLogin;
    // End of variables declaration//GEN-END:variables
}
