package sop_corba.interfazEstudiantesDirectorPackage;


/**
* sop_corba/interfazEstudiantesDirectorPackage/ListAnteproyectosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:26 PM COT
*/

public final class ListAnteproyectosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.anteproyectoDTO value[] = null;

  public ListAnteproyectosHolder ()
  {
  }

  public ListAnteproyectosHolder (sop_corba.anteproyectoDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.interfazEstudiantesDirectorPackage.ListAnteproyectosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.interfazEstudiantesDirectorPackage.ListAnteproyectosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.interfazEstudiantesDirectorPackage.ListAnteproyectosHelper.type ();
  }

}
