package sop_corba;


/**
* sop_corba/anteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:02 PM COT
*/

public final class anteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String atrModalidad = null;
  public String atrTitulo = null;
  public int atrCodigo = (int)0;
  public String atrNombreEstudiante1 = null;
  public String atrNombreEstudiante2 = null;
  public String atrNombreDirector = null;
  public String atrNombreCodirector = null;
  public String atrFechaRegistro = null;
  public String atrFechaAprobacion = null;
  public int atrConcepto = (int)0;
  public int atrEstado = (int)0;
  public int atrNumeroRevision = (int)0;
  public int atrRolAnteproyecto = (int)0;

    public void setAtrModalidad(String atrModalidad) {
        this.atrModalidad = atrModalidad;
    }

    public void setAtrTitulo(String atrTitulo) {
        this.atrTitulo = atrTitulo;
    }

    public void setAtrCodigo(int atrCodigo) {
        this.atrCodigo = atrCodigo;
    }

    public void setAtrNombreEstudiante1(String atrNombreEstudiante1) {
        this.atrNombreEstudiante1 = atrNombreEstudiante1;
    }

    public void setAtrNombreEstudiante2(String atrNombreEstudiante2) {
        this.atrNombreEstudiante2 = atrNombreEstudiante2;
    }

    public void setAtrNombreDirector(String atrNombreDirector) {
        this.atrNombreDirector = atrNombreDirector;
    }

    public void setAtrNombreCodirector(String atrNombreCodirector) {
        this.atrNombreCodirector = atrNombreCodirector;
    }

    public void setAtrFechaRegistro(String atrFechaRegistro) {
        this.atrFechaRegistro = atrFechaRegistro;
    }

    public void setAtrFechaAprobacion(String atrFechaAprobacion) {
        this.atrFechaAprobacion = atrFechaAprobacion;
    }

    public void setAtrConcepto(int atrConcepto) {
        this.atrConcepto = atrConcepto;
    }

    public void setAtrEstado(int atrEstado) {
        this.atrEstado = atrEstado;
    }

    public void setAtrNumeroRevision(int atrNumeroRevision) {
        this.atrNumeroRevision = atrNumeroRevision;
    }

    public void setAtrRolAnteproyecto(int atrRolAnteproyecto) {
        this.atrRolAnteproyecto = atrRolAnteproyecto;
    }

    public String getAtrModalidad() {
        return atrModalidad;
    }

    public String getAtrTitulo() {
        return atrTitulo;
    }

    public int getAtrCodigo() {
        return atrCodigo;
    }

    public String getAtrNombreEstudiante1() {
        return atrNombreEstudiante1;
    }

    public String getAtrNombreEstudiante2() {
        return atrNombreEstudiante2;
    }

    public String getAtrNombreDirector() {
        return atrNombreDirector;
    }

    public String getAtrNombreCodirector() {
        return atrNombreCodirector;
    }

    public String getAtrFechaRegistro() {
        return atrFechaRegistro;
    }

    public String getAtrFechaAprobacion() {
        return atrFechaAprobacion;
    }

    public int getAtrConcepto() {
        return atrConcepto;
    }

    public int getAtrEstado() {
        return atrEstado;
    }

    public int getAtrNumeroRevision() {
        return atrNumeroRevision;
    }

    public int getAtrRolAnteproyecto() {
        return atrRolAnteproyecto;
    }

  public anteproyectoDTO ()
  {
  } // ctor

  public anteproyectoDTO (String _atrModalidad, String _atrTitulo, int _atrCodigo, String _atrNombreEstudiante1, String _atrNombreEstudiante2, String _atrNombreDirector, String _atrNombreCodirector, String _atrFechaRegistro, String _atrFechaAprobacion, int _atrConcepto, int _atrEstado, int _atrNumeroRevision, int _atrRolAnteproyecto)
  {
    atrModalidad = _atrModalidad;
    atrTitulo = _atrTitulo;
    atrCodigo = _atrCodigo;
    atrNombreEstudiante1 = _atrNombreEstudiante1;
    atrNombreEstudiante2 = _atrNombreEstudiante2;
    atrNombreDirector = _atrNombreDirector;
    atrNombreCodirector = _atrNombreCodirector;
    atrFechaRegistro = _atrFechaRegistro;
    atrFechaAprobacion = _atrFechaAprobacion;
    atrConcepto = _atrConcepto;
    atrEstado = _atrEstado;
    atrNumeroRevision = _atrNumeroRevision;
    atrRolAnteproyecto = _atrRolAnteproyecto;
  } // ctor

} // class anteproyectoDTO
