package sop_corba;


/**
* sop_corba/anteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:25 PM COT
*/

public final class anteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String atrModalidad = null;
  public String atrTitulo = null;
  public int atrCodigo = (int)0;
  public String atrIdEstudiante1 = null;
  public String atrIdEstudiante2 = null;
  public String atrIdDirector = null;
  public String atrIdCodirector = null;
  public String atrFechaRegistro = null;
  public String atrFechaAprobacion = null;
  public int atrConcepto = (int)0;
  public int atrEstado = (int)0;
  public int atrNumeroRevision = (int)0;

  public anteproyectoDTO ()
  {
  } // ctor

  public anteproyectoDTO (String _atrModalidad, String _atrTitulo, int _atrCodigo, String _atrIdEstudiante1, String _atrIdEstudiante2, String _atrIdDirector, String _atrIdCodirector, String _atrFechaRegistro, String _atrFechaAprobacion, int _atrConcepto, int _atrEstado, int _atrNumeroRevision)
  {
    atrModalidad = _atrModalidad;
    atrTitulo = _atrTitulo;
    atrCodigo = _atrCodigo;
    atrIdEstudiante1 = _atrIdEstudiante1;
    atrIdEstudiante2 = _atrIdEstudiante2;
    atrIdDirector = _atrIdDirector;
    atrIdCodirector = _atrIdCodirector;
    atrFechaRegistro = _atrFechaRegistro;
    atrFechaAprobacion = _atrFechaAprobacion;
    atrConcepto = _atrConcepto;
    atrEstado = _atrEstado;
    atrNumeroRevision = _atrNumeroRevision;
  } // ctor

} // class anteproyectoDTO
