package sop_corba;


/**
* sop_corba/clsAsigEvaluadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 04:57:34 AM COT
*/

public final class clsAsigEvaluadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String parNomEvaluador1 = null;
  public String parConceptoEVa1 = null;
  public String parFechaRevision1 = null;
  public String parNomEvaluador2 = null;
  public String parConceptoEVa2 = null;
  public String parFechaRevision2 = null;

  public clsAsigEvaluadoresDTO ()
  {
  } // ctor

  public clsAsigEvaluadoresDTO (String _parNomEvaluador1, String _parConceptoEVa1, String _parFechaRevision1, String _parNomEvaluador2, String _parConceptoEVa2, String _parFechaRevision2)
  {
    parNomEvaluador1 = _parNomEvaluador1;
    parConceptoEVa1 = _parConceptoEVa1;
    parFechaRevision1 = _parFechaRevision1;
    parNomEvaluador2 = _parNomEvaluador2;
    parConceptoEVa2 = _parConceptoEVa2;
    parFechaRevision2 = _parFechaRevision2;
  } // ctor

} // class clsAsigEvaluadoresDTO
