package sop_corba;


/**
* sop_corba/clsAsigEvaluadoresDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:27 PM COT
*/

abstract public class clsAsigEvaluadoresDTOHelper
{
  private static String  _id = "IDL:sop_corba/clsAsigEvaluadoresDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.clsAsigEvaluadoresDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.clsAsigEvaluadoresDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "cod_anteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "IdEvaluador1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ConceptoEVa1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "FechaRevision1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "idEvaluador2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "ConceptoEVa2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "FechaRevision2",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.clsAsigEvaluadoresDTOHelper.id (), "clsAsigEvaluadoresDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.clsAsigEvaluadoresDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.clsAsigEvaluadoresDTO value = new sop_corba.clsAsigEvaluadoresDTO ();
    value.cod_anteproyecto = istream.read_long ();
    value.IdEvaluador1 = istream.read_string ();
    value.ConceptoEVa1 = istream.read_string ();
    value.FechaRevision1 = istream.read_string ();
    value.idEvaluador2 = istream.read_string ();
    value.ConceptoEVa2 = istream.read_string ();
    value.FechaRevision2 = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.clsAsigEvaluadoresDTO value)
  {
    ostream.write_long (value.cod_anteproyecto);
    ostream.write_string (value.IdEvaluador1);
    ostream.write_string (value.ConceptoEVa1);
    ostream.write_string (value.FechaRevision1);
    ostream.write_string (value.idEvaluador2);
    ostream.write_string (value.ConceptoEVa2);
    ostream.write_string (value.FechaRevision2);
  }

}
