package sop_corba;


/**
* sop_corba/clsAsigEvaluadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:27 PM COT
*/

public final class clsAsigEvaluadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int cod_anteproyecto = (int)0;
  public String IdEvaluador1 = null;
  public String ConceptoEVa1 = null;
  public String FechaRevision1 = null;
  public String idEvaluador2 = null;
  public String ConceptoEVa2 = null;
  public String FechaRevision2 = null;

  public clsAsigEvaluadoresDTO ()
  {
  } // ctor

  public clsAsigEvaluadoresDTO (int _cod_anteproyecto, String _IdEvaluador1, String _ConceptoEVa1, String _FechaRevision1, String _idEvaluador2, String _ConceptoEVa2, String _FechaRevision2)
  {
    cod_anteproyecto = _cod_anteproyecto;
    IdEvaluador1 = _IdEvaluador1;
    ConceptoEVa1 = _ConceptoEVa1;
    FechaRevision1 = _FechaRevision1;
    idEvaluador2 = _idEvaluador2;
    ConceptoEVa2 = _ConceptoEVa2;
    FechaRevision2 = _FechaRevision2;
  } // ctor

} // class clsAsigEvaluadoresDTO
