package sop_corba;


/**
* sop_corba/interfazUsuarioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 05:26:42 AM COT
*/

public abstract class interfazUsuarioPOA extends org.omg.PortableServer.Servant
 implements sop_corba.interfazUsuarioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("IniciarSesion", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/interfazUsuario/IniciarSesion
       {
         String parUser = in.read_string ();
         String parPassword = in.read_string ();
         int $result = (int)0;
         $result = this.IniciarSesion (parUser, parPassword);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/interfazUsuario:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public interfazUsuario _this() 
  {
    return interfazUsuarioHelper.narrow(
    super._this_object());
  }

  public interfazUsuario _this(org.omg.CORBA.ORB orb) 
  {
    return interfazUsuarioHelper.narrow(
    super._this_object(orb));
  }


} // class interfazUsuarioPOA
