package sop_corba;


/**
* sop_corba/interfazUsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 05:26:42 AM COT
*/

public interface interfazUsuarioOperations 
{
  int IniciarSesion (String parUser, String parPassword);
} // interface interfazUsuarioOperations
