package sop_corba;


/**
* sop_corba/interfazEstudiantesDirectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 05:26:41 AM COT
*/

public interface interfazEstudiantesDirectorOperations 
{
  sop_corba.anteproyectoDTO[] listarAnteProyectos ();
  sop_corba.anteproyectoDTO buscarAnteproyecto (int parCodigo);
} // interface interfazEstudiantesDirectorOperations
