package sop_corba;


/**
* sop_corba/interfazEvaluadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:27 PM COT
*/

public interface interfazEvaluadorOperations 
{
  boolean ingresarConceptoEvaluador (int idUsuario, int parCodigoAnteproyecto, int parConcepto);
} // interface interfazEvaluadorOperations
