package sop_corba;


/**
* sop_corba/interfazEvaluadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:03 PM COT
*/

public interface interfazEvaluadorOperations 
{
  boolean ingresarConcepto (int parCodigoAnteproyecto, String parConcepto);
} // interface interfazEvaluadorOperations
