package sop_corba;


/**
* sop_corba/interfazUsuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 11:25:32 PM COT
*/

public interface interfazUsuario extends interfazUsuarioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfazUsuario
