package sop_corba;


/**
* sop_corba/interfazEstudiantesDirector.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 05:26:41 AM COT
*/

public interface interfazEstudiantesDirector extends interfazEstudiantesDirectorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfazEstudiantesDirector
