package sop_corba;

/**
* sop_corba/interfazUsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 04:57:34 AM COT
*/

public final class interfazUsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.interfazUsuario value = null;

  public interfazUsuarioHolder ()
  {
  }

  public interfazUsuarioHolder (sop_corba.interfazUsuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.interfazUsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.interfazUsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.interfazUsuarioHelper.type ();
  }

}
