package sop_corba;


/**
* sop_corba/interfazAnteProyectosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:03 PM COT
*/

public interface interfazAnteProyectosOperations 
{
  boolean registrarAnteproyecto (sop_corba.anteproyectoDTO objAnteproyecto);
  sop_corba.anteproyectoDTO buscarAnteproyecto (String titulo);
} // interface interfazAnteProyectosOperations
