package sop_corba;


/**
* sop_corba/interfazEstudiantesDirectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:03 PM COT
*/

public interface interfazEstudiantesDirectorOperations 
{
  sop_corba.anteproyectoDTO[] listarAnteProyectos ();
  sop_corba.anteproyectoDTO buscarAnteproyecto (int parCodigo);
} // interface interfazEstudiantesDirectorOperations
