package sop_corba;


/**
* sop_corba/interfazEvaluador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:03 PM COT
*/

public interface interfazEvaluador extends interfazEvaluadorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfazEvaluador
