package sop_corba;


/**
* sop_corba/interfazAnteProyectos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 11:41:26 PM COT
*/

public interface interfazAnteProyectos extends interfazAnteProyectosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfazAnteProyectos
