package sop_corba;


/**
* sop_corba/interfazEvaluadorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 04:57:33 AM COT
*/

public abstract class interfazEvaluadorPOA extends org.omg.PortableServer.Servant
 implements sop_corba.interfazEvaluadorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ingresarConcepto", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/interfazEvaluador/ingresarConcepto
       {
         int parCodigoAnteproyecto = in.read_long ();
         String parConcepto = in.read_string ();
         boolean $result = false;
         $result = this.ingresarConcepto (parCodigoAnteproyecto, parConcepto);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/interfazEvaluador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public interfazEvaluador _this() 
  {
    return interfazEvaluadorHelper.narrow(
    super._this_object());
  }

  public interfazEvaluador _this(org.omg.CORBA.ORB orb) 
  {
    return interfazEvaluadorHelper.narrow(
    super._this_object(orb));
  }


} // class interfazEvaluadorPOA
