package sop_corba;


/**
* sop_corba/interfazJefeDepartamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* sábado 3 de agosto de 2019 04:57:34 AM COT
*/

public interface interfazJefeDepartamento extends interfazJefeDepartamentoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfazJefeDepartamento
