package sop_corba;


/**
* sop_corba/UsuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 11:25:31 PM COT
*/

public final class UsuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String nombre = null;
  public String apellido = null;
  public String usuario = null;
  public String password = null;
  public int tipo = (int)0;

  public UsuarioDTO ()
  {
  } // ctor

  public UsuarioDTO (String _id, String _nombre, String _apellido, String _usuario, String _password, int _tipo)
  {
    id = _id;
    nombre = _nombre;
    apellido = _apellido;
    usuario = _usuario;
    password = _password;
    tipo = _tipo;
  } // ctor

} // class UsuarioDTO
