package sop_corba;


/**
* sop_corba/UsuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfazAnteproyecto.idl
* viernes 2 de agosto de 2019 08:20:03 PM COT
*/

public final class UsuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String nombre = null;
  public String apellido = null;
  public String usuario = null;
  public String password = null;

    public void setId(String id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public String getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public String getUsuario() {
        return usuario;
    }

    public String getPassword() {
        return password;
    }

    public int getTipo() {
        return tipo;
    }
  public int tipo = (int)0;

  public UsuarioDTO ()
  {
  } // ctor

  public UsuarioDTO (String _id, String _nombre, String _apellido, String _usuario, String _password, int _tipo)
  {
    id = _id;
    nombre = _nombre;
    apellido = _apellido;
    usuario = _usuario;
    password = _password;
    tipo = _tipo;
  } // ctor

} // class UsuarioDTO
